services:
  gimp:
    image: lscr.io/linuxserver/gimp:latest
    container_name: gimp
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/docker/gimp:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
