services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /data/docker/homeassistant/conf:/config
      - /data/docker/homeassistant/templates:/config/custom_templates
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://<your-domain>:8123"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 8123:8123
    privileged: true
